### ISSUE TITLE
Use env file instead of config

### ISSUE THREAD

**Issue by thisisommore** [MyriadFlow/marketplace#4]
<a href="https://github.com/thisisommore"><img src="https://avatars.githubusercontent.com/u/51229945?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [thisisommore](https://github.com/thisisommore)**
_Thursday Mar 17, 2022 at 05:34 GMT_
_Originally opened as https://github.com/TheLazarusNetwork/marketplace-webapp/issues/11_

----

**Comment by emily876** [comment]
It is done. Right? @thisisommore

**Comment by thisisommore** [comment]
> It is done. Right? @thisisommore 

Yes
